language: cpp
sudo: false
dist: trusty

addons:
  apt:
    packages:
      - srecord
      - gcovr

env:
    global:
        - CODECOV_TOKEN=:uuid-repo-token


install:
  - ./autogen.sh
  - ./configure --enable-gcov

script: 
  - make
  - make firmware_tool
  - make server
  - make assets
  - ./utils/server/server -f assets/fake_firmware_dead >/dev/null 2>&1 &
  - make check

after_success:
  - bash <(curl -s https://codecov.io/bash)
