language: cpp
sudo: false
dist: trusty

addons:
  apt:
    packages:
      - gcovr

before_install:
  - export CC=gcc-4.9
  - export CXX=g++-4.9
  - g++ --version
install:
  - ./autogen.sh
  - ./configure

script: 
  - make
  - make firmware_tool
  - make server
  - make assets
  - make run_server &
  - make check
