language: cpp
sudo: false
dist: trusty

addons:
  apt:
    packages:
      - srecord
      - gcovr

install:
  - ./autogen.sh
  - ./configure

script: 
  - make
  - make firmware_tool
  - make server
  - make assets
  - ./utils/server/server -f assets/fake_firmware_dead >/dev/null 2>&1 &
  - make check
