language: cpp
sudo: false
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - srecord
      - gcovr
      - g++-4.9

before_install:
  - export CC=gcc-4.9
  - export CXX=g++-4.9
  - g++ --version
install:
  - gem install ceedling
  - ./autogen.sh
  - (cd utils/server/ && make)
  - ./utils/server/server.bin -a assets & >/dev/null 2>&1

script: ceedling test:all
