# This is a configuration file for the firmware_tool utility

title = "Configuration Example"

[firmware configurations]
version = 0xdead
platform = 0xbeef
offset = 0x100

[paths]
signature_file = "signature.bin"
binary_file = "firmware.hex"
out_file = "manifest.bin"

[keys] 
server_priv_key = "keys/server.priv"
server_pub_key = "keys/server.pub"
vendor_priv_key = "keys/vendor.priv"
vendor_pub_key = "keys/vendor.pub"
